# Generated by Django 4.2.11 on 2024-07-11 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('task', models.TextField(max_length=500)),
                ('dead_line', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
